version: '3.8'

services:
  # 프론트엔드 서비스
  ta-go-frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_DATE: ${BUILD_DATE:-$(date -u +'%Y-%m-%dT%H:%M:%SZ')}
    container_name: ta-go-frontend
    ports:
      - "3011:3011"
    environment:
      - NODE_ENV=production
      - PORT=3011
      - NEXT_PUBLIC_API_URL=http://ta-go.shop
      - NEXT_PUBLIC_API_GRAPHQL_URL=http://ta-go.shop/graphql
      - NEXT_PUBLIC_API_WS=ws://ta-go.shop
    restart: unless-stopped
    networks:
      - ta-go-network

  # 백엔드 서비스
  ta-go-backend:
    build:
      context: ./server
      dockerfile: Dockerfile.backend
    container_name: ta-go-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    networks:
      - ta-go-network

  # Nginx 리버스 프록시
  nginx:
    image: nginx:alpine
    container_name: ta-go-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - ta-go-frontend
      - ta-go-backend
    restart: unless-stopped
    networks:
      - ta-go-network

networks:
  ta-go-network:
    driver: bridge
