export enum PropertyType {
	ADVENTURE_TOURERS = 'ADVENTURE_TOURERS',
	AGRICULTURE = 'AGRICULTURE',
	ALL_TERRAIN_VEHICLES = 'ALL_TERRAIN_VEHICLES',
	DIRT = 'DIRT',
	ELECTRIC = 'ELECTRIC',
	ENDURO = 'ENDURO',
	MINI_BIKES = 'MINI_BIKES',
	SXS_UTV = 'SXS_UTV',
}

export enum PropertyStatus {
	AVAILABLE = 'AVAILABLE',
	SOLD = 'SOLD',
	RESERVED = 'RESERVED',
	UNAVAILABLE = 'UNAVAILABLE',
}

export enum PropertyCondition {
	NEW = 'NEW',
	LIKE_NEW = 'LIKE_NEW',
	EXCELLENT = 'EXCELLENT',
	GOOD = 'GOOD',
	FAIR = 'FAIR',
	POOR = 'POOR',
}

export enum PropertyLocation {
	SEOUL = 'SEOUL',
	BUSAN = 'BUSAN',
	INCHEON = 'INCHEON',
	DAEGU = 'DAEGU',
	GYEONGGI = 'GYEONGGI',
	GWANGJU = 'GWANGJU',
	JEONBUK = 'JEONBUK',
	DAEJEON = 'DAEJEON',
	JEJU = 'JEJU',
	ULSAN = 'ULSAN',
	GANGWON = 'GANGWON',
	CHUNGBUK = 'CHUNGBUK',
	CHUNGNAM = 'CHUNGNAM',
	JEONNAM = 'JEONNAM',
	GYEONGBUK = 'GYEONGBUK',
	GYEONGNAM = 'GYEONGNAM',
}

export enum FuelType {
	GASOLINE = 'GASOLINE',
	DIESEL = 'DIESEL',
	ELECTRIC = 'ELECTRIC',
	HYBRID = 'HYBRID',
	LPG = 'LPG',
}

export enum TransmissionType {
	MANUAL = 'MANUAL',
	AUTOMATIC = 'AUTOMATIC',
	CVT = 'CVT',
	SEMI_AUTO = 'SEMI_AUTO',
}
